# Long Haul

trigger:
  batch: true
  branches:
    include:
    - main

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

variables:
    spinxskRuntime: 1440
    spinxskTimeout: 1445
    spinxskJobTimeout: 1455

stages:

- stage: build_debug
  displayName: Build (Debug)
  dependsOn: []
  jobs:
  - template: ./templates/build.yml
    parameters:
      arch: x64
      config: Debug

- stage: stress_debug
  displayName: Stress (Debug)
  dependsOn:
  - build_debug
  jobs:
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WS2019-Spinxsk
      arch: x64
      config: Debug
      osName: 2019
      xdpmpPollProvider: FNDIS
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}
  - template: ./templates/spinxsk.yml
    parameters:
      pool: XDP-CI-1ES-Spinxsk-2
      image: WS2022-Spinxsk
      arch: x64
      config: Debug
      osName: 2022
      xdpmpPollProvider: FNDIS
      runtimeMinutes: ${{ variables.spinxskRuntime }}
      timeoutMinutes: ${{ variables.spinxskTimeout }}
      jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}
  # Prerelease stress is disabled due to a Windows bug
  # - template: ./templates/spinxsk.yml
  #   parameters:
  #     pool: XDP-CI-1ES-Spinxsk-2
  #     image: WSPrerelease-Spinxsk
  #     arch: x64
  #     config: Debug
  #     osName: Prerelease
  #     xdpmpPollProvider: FNDIS
  #     runtimeMinutes: ${{ variables.spinxskRuntime }}
  #     timeoutMinutes: ${{ variables.spinxskTimeout }}
  #     jobTimeoutMinutes: ${{ variables.spinxskJobTimeout }}
